{{- if .Values.service.enabled -}}
{{- $fullName := include "helm-starter.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "helm-starter.name" . }}
    chart: {{ template "helm-starter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $key, $value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ default $value.port $value.targetPort }}
      name: {{ $value.name }}
{{- end }}
  selector:
    app: {{ template "helm-starter.name" . }}
    release: {{ .Release.Name }}
{{- end }}